CREATE DATABASE freqwatch;
CREATE USER 'freqwatch'@'localhost' IDENTIFIED BY 'passwd';
GRANT ALL PRIVILEGES ON freqwatch.* TO 'freqwatch'@'localhost' WITH GRANT OPTION;
USE freqwatch;
CREATE TABLE intercepts (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, date DATE, time TIME, freq INT UNSIGNED, data MEDIUMBLOB);
CREATE TABLE freqs (id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, date DATE, time TIME, freq INT UNSIGNED, power FLOAT);

